const { invoke } = window.__TAURI__ ? window.__TAURI__.invoke : { invoke: async ()=>null };
function normLang(l){l=(l||'en').toString().trim().toLowerCase();if(l==='pt'||l==='pt-pt'||l==='pt_pt')return 'pt-PT';return l}
function buildLangSelector(){const sel=document.getElementById('lang-select');const desired=['en','en-GB','es','es-419','pt-PT','pt-BR','fr','de','it','ru','bg','ca','cs','da','el','et','fa','fi','fil','gu','he','hi','hr','hu','id','ja','kn','ko','lt','lv','ml','mr','ms','nb','nl','pl','ro','sk','sl','sr','sv','sw','ta','te','th','tr','uk','ur','vi','zh-CN','zh-TW'];sel.innerHTML='';desired.forEach(code=>{const o=document.createElement('option');o.value=code;o.text=code.toUpperCase();sel.appendChild(o)});let cur=normLang(localStorage.getItem('titanes.lang'));sel.value=cur;sel.onchange=function(){localStorage.setItem('titanes.lang',sel.value);applyI18n();}}
async function loadDict(lang){lang=normLang(lang);if(lang==='en')return {};try{const r=await fetch('locales_cf/'+lang+'.json');if(r.ok){return await r.json()}return {}}catch(_){return {}}}
function applyText(el,dict){const key=el.getAttribute('data-i18n');if(!key)return;const val=dict[key];if(val){el.textContent=val}}
function applyAttrs(el,dict){const map=[['placeholder','data-i18n-placeholder']];for(const [attr,meta] of map){const k=el.getAttribute(meta);if(k&&dict[k]){el.setAttribute(attr,dict[k])}}}
async function applyI18n(){const lang=normLang(localStorage.getItem('titanes.lang')||'en');const dict=await loadDict(lang);document.querySelectorAll('[data-i18n]').forEach(el=>applyText(el,dict));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>applyAttrs(el,dict))}
async function wire(){buildLangSelector();await applyI18n();document.getElementById('login').onclick=async function(){const u=document.getElementById('user').value;const p=document.getElementById('pass').value;let ok=false;try{ok=await invoke('warperia_login',{user:u,pass:p})}catch(_){ok=true}document.getElementById('login-status').textContent= ok? 'OK':'FAIL'};document.getElementById('refresh').onclick=async function(){let data=null;try{data=await invoke('list_servers')}catch(_){data={servers:[]}}const ul=document.getElementById('servers');ul.innerHTML='';(data.servers||[]).forEach(s=>{const li=document.createElement('li');li.textContent=s.name+' ('+s.status+')';ul.appendChild(li)})}}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',wire)}else{wire()}
